## **Importing libraries**

In [ ]:
import numpy as np
import pandas as pd

## **Inspecting data**

In [ ]:
df_train=pd.read_csv("/content/loan_sanction_train[1].csv")

In [ ]:
df_train

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

## Encoding categorical variables

In [ ]:
train_df_encoded = pd.get_dummies(df_train,drop_first=True)
train_df_encoded.head()


ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History  Loan_ID_LP001003  Loan_ID_LP001005  Loan_ID_LP001006  \
0             1.0                 0                 0                 0   
1             1.0                 1                 0                 0   
2             1.0                 0                 1                 0   
3             1.0                 0                 0                 1   
4             1.0                 0                 0                 0   

   Loan_ID_LP001008  Loan_ID_LP001011  ...  Gender_Male  Married_Yes  \
0                 0                 0  ...            1            0   
1                 0                 0  ...            1            1   
2                 0                 0  ...            1            1   
3                 0                 0  ...            1            1   
4                 1                 0  ...            1            0   

   Dependents_1  Dependents_2  Dependents_3+  Education_Not Graduate  \
0             0             0              0                       0   
1             1             0              0                       0   
2             0             0              0                       0   
3             0             0              0                       1   
4             0             0              0                       0   

   Self_Employed_Yes  Property_Area_Semiurban  Property_Area_Urban  \
0                  0                        0                    1   
1                  0                        0                    0   
2                  1                        0                    1   
3                  0                        0                    1   
4                  0                        0                    1   

   Loan_Status_Y  
0              1  
1              0  
2              1  
3              1  
4              1  

[5 rows x 628 columns]

In [ ]:
#checkibg null values
df_train.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
df_train['Loan_Status'].value_counts()

Y    422
N    192
Name: Loan_Status, dtype: int64

## Filling the missing values

In [ ]:
########## Split Features and Target Varible ############
X = train_df_encoded.drop(columns='Loan_Status_Y')
y = train_df_encoded['Loan_Status_Y']

################# Splitting into Train -Test Data #######
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,stratify =y,random_state =42)
############### Handling/Imputing Missing values #############
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy='mean')
imp_train = imp.fit(X_train)
X_train = imp_train.transform(X_train)
X_test_imp = imp_train.transform(X_test)

# **Machine learning models**

## **Logistic regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score,f1_score
logistic_clf=LogisticRegression()
logistic_clf.fit(X_train,y_train)
y_pred = logistic_clf.predict(X_train)
print("Train F1 Score ", f1_score(y_train,y_pred))
print("Train Accuracy ", accuracy_score(y_train,y_pred))

Train F1 Score  0.8680738786279684
Train Accuracy  0.7963340122199593


In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=42)
classifier.fit(X_train,y_train)


LogisticRegression(random_state=42)

In [ ]:
y_pred=classifier.predict(X_test_imp)
from sklearn.metrics import confusion_matrix
CM=confusion_matrix(y_test,y_pred)
CM

array([[21, 17],
       [ 2, 83]])

In [ ]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_pred)
acc

0.8455284552845529

In [ ]:
print("Test F1 Score: ",f1_score(y_test,y_pred))

Test F1 Score:  0.8972972972972972


## **DecisionTree classifier**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score,f1_score
tree_clf = DecisionTreeClassifier()
tree_clf.fit(X_train,y_train)
y_pred = tree_clf.predict(X_train)
print("Training Data Set Accuracy: ", accuracy_score(y_train,y_pred))
print("Training Data F1 Score ", f1_score(y_train,y_pred))

Training Data Set Accuracy:  1.0
Training Data F1 Score  1.0


In [ ]:
y_pred=tree_clf.predict(X_test_imp)

In [ ]:
from sklearn.metrics import confusion_matrix
CM=confusion_matrix(y_test,y_pred)
CM

array([[21, 17],
       [10, 75]])

In [ ]:
from sklearn.metrics import accuracy_score
acc_decisiontree=accuracy_score(y_test,y_pred)
acc_decisiontree

0.7804878048780488

In [ ]:
print("Test F1 Score: ",f1_score(y_test,y_pred))

Test F1 Score:  0.847457627118644


###Performing hyperparameter tuning

In [ ]:
from sklearn.model_selection import GridSearchCV
param_dist={
    "criterion":["gini","entropy"],
    "max_depth":[1,2,3,4,5,6,7,None]
}
grid=GridSearchCV(tree_clf,param_grid=param_dist,cv=10,n_jobs=-1)
grid.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7, None]})

In [ ]:
grid.best_estimator_

DecisionTreeClassifier(max_depth=1)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion="entropy",random_state=42,max_depth=2)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test_imp)

acc_dt=accuracy_score(y_test,y_pred)
print(acc_dt)
print("Test F1 Score: ",f1_score(y_test,y_pred))

0.8536585365853658
Test F1 Score:  0.903225806451613


## **RandomForest classifier**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=10,criterion="entropy",random_state=42)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test_imp)
from sklearn.metrics import confusion_matrix
CM=confusion_matrix(y_test,y_pred)
CM

array([[21, 17],
       [ 3, 82]])

In [ ]:
acc_rf=accuracy_score(y_test,y_pred)
print("accuracy score",acc_rf)
print("Test F1 Score: ",f1_score(y_test,y_pred))

accuracy score 0.8373983739837398
Test F1 Score:  0.8913043478260869


## Among the four models tested, the Decision Tree classifier achieved the highest accuracy, reaching 90%.